
globals:
  project_home: $APOLLO_HOME
  service_module: apollo_services
  datastore_module: apollo_datastores


services:

datastores:
  fileds:
    class: FileStore
    init_params:
      - name: filename
        value: foobar.txt

      - name: fail_if_not_found
        value: True

ingest_targets:
  test: 
    datastore: fileds
    checkpoint_interval: 1

